keys:
  # Users
  - &users:
    - &jocelyn 00E063D5E30126C1A3DF114E77B3416DE9D092BD
  # Hosts
  - &hosts:
    - &desktek age1cf355lw4hznu9qef2vcejls926fhvmvwjnm8s3a5ghvktvtspd5svp5qg8
    - &frametek age1tsgsllypatl2303talc094gjq9achlwzms0ky2q24fu647sq6aqqyv8s7s
    - &servetek age1tk4xmr6ye60naj0zvxjv6l7q9zdhj05z67m98ph4qar6jczslcqqsvhqs4

creation_rules:
  - path_regex: secrets/servetek/secrets.ya?ml$
    key_groups:
    - age:
      - *servetek
      pgp:
      - *jocelyn
  - path_regex: secrets/common/secrets.ya?ml$
    key_groups:
    - age:
      - *desktek
      - *frametek
      - *servetek
      pgp:
      - *jocelyn

