keys:
  # Users
  users: &users
    - &jocelyn 00E063D5E30126C1A3DF114E77B3416DE9D092BD
  # Hosts
  hosts: &hosts
    - &desktek age1cf355lw4hznu9qef2vcejls926fhvmvwjnm8s3a5ghvktvtspd5svp5qg8
    - &frametek age1sgcdrv8mjlt705dteks9ke4jmlq6fqn244hakfcv5zwjmpc7xu5q893kna
    - &servetek age1zhp9k6f3nu9ljrwd5lgtef7pldwfqfq8l6m8g9v4z23wzejnaemq22sj6k

creation_rules:
  - path_regex: secrets/servetek/secrets.ya?ml$
    key_groups:
    - age:
      - *servetek
      pgp:
      - *jocelyn
  - path_regex: secrets/common/secrets.ya?ml$
    key_groups:
    - age: *hosts
      pgp: *users

