name: Cachix
on:
  workflow_run:
    workflows: ["Update"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        host:
          - desktek
          - frametek
          - servetek
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v17
        with:
          name: tekila
          extraPullNames: nix-community,devenv,noctalia
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build ${{ matrix.host }}
        run: nix build '.#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel'
