name: Cachix

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: cachix/install-nix-action@v18
      - name: Cachix
        uses: cachix/cachix-action@v12
        with:
          name: tekila
          extraPullNames: 'cache,nix-community,hyprland,devenv,statix'
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true
      - name: Dead code analysis
        uses: astro/deadnix-action@main
      - name: Lint code
        uses: jocelynthode/statix-action@0.1
      - run: nix build -L --no-link .#nixosConfigurations.desktek.config.system.build.toplevel
      - run: nix eval --json ".#nixosConfigurations.desktek.config.system.build.toplevel.outPath" | sed 's/"\(.*\)"/\1/' | cachix push tekila
      - run: nix build -L --no-link .#nixosConfigurations.frametek.config.system.build.toplevel
      - run: nix eval --json ".#nixosConfigurations.frametek.config.system.build.toplevel.outPath" | sed 's/"\(.*\)"/\1/' | cachix push tekila
      - run: nix build -L --no-link .#nixosConfigurations.servetek.config.system.build.toplevel
      - run: nix eval --json ".#nixosConfigurations.servetek.config.system.build.toplevel.outPath" | sed 's/"\(.*\)"/\1/' | cachix push tekila
