name: Iso

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Install Nix'
        uses: cachix/install-nix-action@v25
      - name: 'Check NixOS Flake'
        run: nix flake check
      - name: 'Build Iso'
        run: nix build '.#nixosConfigurations.iso.config.system.build.isoImage'
      - name: Release ISO
        uses: softprops/action-gh-release@v1
        with:
          files: result/iso/*
