name: Iso

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: "Install Nix"
        uses: cachix/install-nix-action@v31
      - name: "Build Iso"
        run: nix-build -A nixosConfigurations.iso.config.system.build.isoImage
      - name: Release ISO
        uses: softprops/action-gh-release@v2
        with:
          files: result/iso/*
